name: Android Build

"on":
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Cache pip dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    
    - name: Cache Buildozer global directory
      uses: actions/cache@v3
      with:
        path: .buildozer_global
        key: ${{ runner.os }}-buildozer-global-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-global-
    
    - name: Cache Buildozer directory
      uses: actions/cache@v3
      with:
        path: .buildozer
        key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}
        restore-keys: |
          ${{ runner.os }}-buildozer-
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          python3-dev \
          python3-pip \
          python3-venv \
          openjdk-11-jdk \
          unzip \
          zlib1g-dev \
          libncurses5-dev \
          libncursesw5-dev \
          libtinfo5 \
          cmake \
          libffi-dev \
          libssl-dev \
          automake \
          autoconf \
          libtool \
          pkg-config
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cython
        pip install buildozer
        pip install -r requirements.txt
    
    - name: Set up Java environment
      run: |
        export JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64
        echo "JAVA_HOME=/usr/lib/jvm/java-11-openjdk-amd64" >> $GITHUB_ENV
    
    - name: Set BUILDOZER_GLOBAL_DIR
      run: |
        echo "BUILDOZER_GLOBAL_DIR=${{ github.workspace }}/.buildozer_global" >> $GITHUB_ENV
    
    - name: Initialize Buildozer
      run: |
        export PATH=$PATH:~/.local/bin
        buildozer android debug --verbose
    
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      if: success()
      with:
        name: better-lyrics-debug-apk
        path: bin/*.apk
        retention-days: 30
    
    - name: Upload build logs
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: build-logs
        path: |
          .buildozer/android/platform/build-*/**/*.log
          .buildozer/android/logs/*.log
        retention-days: 7