name: Build Better Lyrics Android APK (Specialized)

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master  
  workflow_dispatch:

jobs:
  build-android-specialized:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Buildozer
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: buildozer android debug
        buildozer_version: stable

    - name: List build output
      run: |
        find . -name "*.apk" -type f -ls || echo "No APK files found"
        ls -la bin/ || echo "No bin directory found"
        ls -la .buildozer/android/platform/ || echo "No platform build directory found"

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      if: success() || failure()
      with:
        name: better-lyrics-android-apk-specialized
        path: |
          bin/*.apk
          .buildozer/android/platform/build-**/outputs/apk/**/*.apk
        retention-days: 30
